### ISSUE TITLE
Change the Design Guide URL in the ReadMe-en.md

### ISSUE THREAD

**Issue by tolgaaaltas** [DellZHackintosh/fluent-flarum#1]
The design guide page in the readme document prepared in English is linked to the document prepared in Chinese. The design guide link should be linked to the document prepared in English.

**Comment by zDaleZ** [comment]
Thank you for pointing out! I've fixed the mistake. ❤️

**Comment by zDaleZ** [comment]
Thank you for pointing out! I've fixed the mistake. ❤️
